---
title: "Untitled"
output: html_document
date: "2023-10-26"
---

```{r}
load("/data/projects/punim1466/analysis/novaseq_virus_trim/seurat/adult_sample_split_sct_donor/sctransform_v2/v1_notidy/split_1_4_9_10_12/sub_RNA_5.RData")

small = readRDS("~/projects/small.Rds")
```

```{r}
library(Seurat)
library(tidyverse)
```

```{r}
dim(sub_5)

small = sub_5[, sample(123128, 10000, replace = FALSE)]

small$celltype <- recode(small@active.ident,

                      '0'='Suprabasal',
                      '1_0'='Secretory-1',
                      '1_1'='Secretory-1',
                      '1_2'='Secretory-1',
                      '1_3'='Secretory-1',
                      '1_4'='Secretory-1',
                      '1_5'='Goblet',
                      '1_6'='Secretory-1',
                      '1_7'='Goblet-Ionocyte',
                      '2'	="Basal-1",
                      '3'	="Ciliated-1",
                      '4_0'	="Goblet",
                      '4_1'	="Secretory-2",
                      '4_2'	="Goblet",
                      '4_3'	="Secretory-2",
                      '4_4'	="Secretory-2",
                      '4_5'	="Secretory-2",
                      '4_6'	="Secretory-2",
                      '4_7'	="Secretory-2",
                      '4_8'	="Secretory-2",
                      '5'	="Ciliated-3",
                      '6'	="Cycling-basal",
                      '7'	="Ciliated-2",
                      '8'	="Basal-2",
                      '9_0'	="Ciliated+SC2",
                      '9_1'	="Secretory-Ciliated+SC2",
                      '10_0' ="Goblet+IFN-stim",
                      '10_1' ="Secretory-3",
                      '10_2' ="Secretory-3",
                      '10_3' ="Secretory-3",
                      '10_4' ="Goblet+IFN-stim",
                      '10_5' ="Secretory-3",
                      '10_6' ="Secretory-3",
                      '10_7' ="Secretory-3",
                      '11'	="Deuterosomal",
                      '12_0' = "Ionocyte",
                      '12_1' = "Brush/Tuft",
                      '13' = "Secretory-Ciliated"
)
```

```{r}
library(slingshot)


sce = as.SingleCellExperiment(small, assay = "SCT" )

sce2 <- slingshot(sce, clusterLabels = 'celltype', reducedDim = 'UMAP')
```

```{r}
library(grDevices)
library(RColorBrewer)
colors <- colorRampPalette(brewer.pal(11,'Spectral')[-6])(100)
plotcol <- colors[cut(sce2$slingPseudotime_1, breaks=100)]


plot(reducedDims(sce2)$UMAP, col = plotcol, pch=16, asp = 1)
lines(SlingshotDataSet(sce2), lwd=2, col='black')
```
```{r}
pseudo = as.data.frame(cbind(sce2$slingPseudotime_1, sce2$slingPseudotime_2, sce2$slingPseudotime_3, 
               sce2$slingPseudotime_4, sce2$slingPseudotime_5, sce2$slingPseudotime_6, sce2$slingPseudotime_7) )

pseudo$row = 1:10000
pseudo %>% as_tibble() %>% 
  pivot_longer(-row) %>%
  group_by(row) %>% summarise(m = mean(value, na.rm = TRUE)) -> x
sce2$slingPseudotime_combined = x$m

plotcol <- colors[cut(sce2$slingPseudotime_combined, breaks=100)]

pdf("../plots/slingshot.pdf")
plot(reducedDims(sce2)$UMAP, col = plotcol, pch=16, asp = 1)
lines(SlingshotDataSet(sce2), lwd=2, col='black')
dev.off()
```
## Monocle

```{r}
library(monocle3)
library(SeuratWrappers)



cds <- as.cell_data_set(small)

plot_cells(cds, color_cells_by = "celltype", show_trajectory_graph = FALSE)

cds <- cluster_cells(cds, resolution=1e-3)

cds <- learn_graph(cds, use_partition = TRUE, verbose = FALSE)

plot_cells(cds,
           color_cells_by = "celltype",
           label_groups_by_cluster=TRUE,
           label_leaves=FALSE,
           label_branch_points=FALSE)
```
```{r}
cds <- order_cells(cds)

pdf("../plots/monocle.pdf",7,6)
plot_cells(cds,
           color_cells_by = "pseudotime",
           group_cells_by = "celltype",
           label_cell_groups = FALSE,
           label_groups_by_cluster=FALSE,
           label_leaves=FALSE,
           label_branch_points=FALSE,
           label_roots = FALSE,
           trajectory_graph_color = "black")
dev.off()
```
